{
 "title": "AIOps - RED Metrics (Checkout)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Request Rate (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=\"500\"}[1m])) / sum(rate(http_requests_total[1m])) * 100"
    }
   ]
  },
  {
   "title": "Average Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])"
    }
   ]
  }
 ]
}